### ISSUE TITLE
Login flow doesn't work when using Cursor.

### ISSUE THREAD

**Issue by paul-freeman** [DataDog/datadog-for-vscode#19]
I recently gave [Cursor](https://www.cursor.com/) a try. Being a fork of VS Code, I found all my extensions worked fine, except for DataDog.

The DataDog extension still asked me to login, and clicking this directed me to my browser. But the browser page wouldn't redirect me back to Cursor, due to it not being a Microsoft redirect (It started with `cursor:/`). It instead gave me a token to copy/paste into Cursor. However, there was no place for me to paste the token and complete the login process.

**Comment by robertohuertasm** [comment]
Hi @paul-freeman, thank you for reaching out and bringing this to our attention.

Currently, this specific use case is not supported. However, we are aware of the issue and it is on our backlog. We understand the importance of this feature and will update this GitHub issue as soon as it is implemented.

**Comment by robertohuertasm** [comment]
fyi @paul-freeman and @jfurie, we have just released [v1.16.0](https://github.com/DataDog/datadog-for-vscode/releases/tag/v1.16.0) with support for [Cursor](https://www.cursor.com/), [VS Codium](https://vscodium.com/) and similar VS Code-based IDEs. 

You will know find an option to enter the code in the extension. Let us know if it works for you.

**Comment by jfurie** [comment]
@robertohuertasm i gave it a try. flow works until i put in the auth code. getting a 400 error

```
2024-09-20 13:48:07.752 [error] 400 [Bad Request] 400 [Bad Request] core.connection.exchangeOAuthCode {"server":"https://app.datadoghq.com","statusCode":400,"statusMessage":"Bad Request"}
2024-09-20 13:48:07.753 [error] shell.connection.oauth: error while waiting for callback from code exchange 400 [Bad Request]
```

**Comment by paul-freeman** [comment]
@robertohuertasm Works well for me! Thanks for the fix!

**Comment by robertohuertasm** [comment]
@jfurie, what is the region of your Datadog account? It seems you may need to change the oAuth domain. By default it uses US1. 

Go to the settings, and change it to the URL of the region you're using:

- EU: app.datadoghq.eu
- US1: app.datadoghq.com
- US3: us3.datadoghq.com
- US5: us5.datadoghq.com
- AP1 (Japan): ap1.datadoghq.com

<img width="447" alt="image" src="https://github.com/user-attachments/assets/f48303b4-7120-4027-9e04-9332d69b4e75">

Let me know if that did the trick.

**Comment by jfurie** [comment]
Sorry i missed your response @robertohuertasm ! yes changing the url to US5 worked for me! thank you for the help!

**Comment by oeuftete** [comment]
I can open a new issue, but should this work for Windsurf as well? I don't see any place to add the code I get back.

![Image](https://github.com/user-attachments/assets/cb597b31-f989-483a-a22b-471d5b66f41b)
