### ISSUE TITLE
Login to extension in cursor

### ISSUE THREAD

**Issue by jfurie** [DataDog/datadog-for-vscode#21]
Trying to log into the extension using cursor editor (fork of vscode), and having issue below:

![image](https://github.com/user-attachments/assets/f84c880a-7f26-4a69-a4f2-b323de931352)

Not sure best way to move forward to login. could use help or improvement to redirect flow to not get stuck on this page. Other extensions I've signed in with have not had this issue so far.

**Comment by robertohuertasm** [comment]
Hi @jfurie, thank you for reporting this ❤️ . Please see the answer to issue #19. We have a potential solution that may be released soon. We’ll keep you all posted.

**Comment by robertohuertasm** [comment]
@jfurie, we have released a new version with a solution for this. Please , check #19 out for more details.
