### ISSUE TITLE
Code Insights says "none applicable to your settings"

### ISSUE THREAD

**Issue by pbernery** [DataDog/datadog-for-vscode#22]
I've installed the extension, and I believe I've set it up, but it is still saying Code Insights are not applicable to my settings.

![Image](https://github.com/user-attachments/assets/37a4ba1e-ee5a-42f4-8e5c-84eb1c16087d)

I have services displayed in the extension:
![Image](https://github.com/user-attachments/assets/60b29ca8-279a-4a56-a007-1579928de2b5)

I have some issues on datadog.eu for the back service, that I expect to see in VSCode when this extension is enabled.
I don't know what to check to make sure Code Insights work?

**Comment by robertohuertasm** [comment]
Hi @pbernery, just double checking:
- are you signed in to the correct account/organization?
- what do you have in the status bar? You should be seeing your org, the range, and the environment. 
![Image](https://github.com/user-attachments/assets/fb13e42c-13d3-490c-ad7a-919c67b457c2)

- are you in the right repository?
- what kind of issues you have in that back service? We're currently supporting Error Tracking issues from APM, Code and Library vulnerabilities and Flaky Tests.

**Comment by pbernery** [comment]
Hi @robertohuertasm ,

- I am signed in to the correct organization, I see its name in the status bar as indicated 👍,
- I am in the right repository,
- I have issues detected by APM (on a Ruby on Rails app).

Don't know if it can help: I use successfully the "View in VS Code" button on the Web interface, to open the source code in VS Code ![Image](https://github.com/user-attachments/assets/db859e62-8b73-4592-88af-4b6625c8494c)

**Comment by pbernery** [comment]
This week, I can see some issues, though I need to click "reload" after opening my project in VSCode:
![Image](https://github.com/user-attachments/assets/05bc1075-5cf9-4e5f-86b1-4204310c6ab8)

I only see recent issues though, while I have older issues and the filter is set to have the issues from last month:
![Image](https://github.com/user-attachments/assets/5dda9c98-fefc-427b-960b-d49b1d0dc8e5)
![Image](https://github.com/user-attachments/assets/fee5ca0e-3eb8-4b05-acee-40a1b6c8fb8c)

**Comment by robertohuertasm** [comment]
Hi @pbernery, thank you for your feedback. That's really valuable. We're investigating your issue. Will come back to you when we have more information.

**Comment by robertohuertasm** [comment]
@pbernery One thing I completely missed to mention is that we only show the Runtime Errors occurred in the last 24h, regardless of the time range you have selected. That would explain why you're only seeing those 3 errors in there.

While this is the current behaviour of the extension we're currently working on increasing this range.

I've been looking through the traces of your requests and everything seems to be fine.

The only thing that feels off is that you need to reload to get those code insights. The extension is making a request when a project is loaded. Does that happen consistently?

**Comment by pbernery** [comment]
>@pbernery One thing I completely missed to mention is that we only show the Runtime Errors occurred in the last 24h, regardless of the time range you have selected. That would explain why you're only seeing those 3 errors in there.
> While this is the current behaviour of the extension we're currently working on increasing this range.

That explains much of the issue :), good to know, and looking forward to see this increase.

> The only thing that feels off is that you need to reload to get those code insights. The extension is making a request when a project is loaded. Does that happen consistently?

Yes. I tried many times to restart VSCode, and each time it shows the "no insights applicable" pane, then I reload and it shows some issues.

**Comment by robertohuertasm** [comment]
Thanks for the feedback. Also, remember that we will only show the code insights related to the services that you have filtered on if you have set the service filters. In your case, you had some services in there, one of them being `back`. 

Can you double check what's the service associated to the old error tracking issue you posted before?

![Image](https://github.com/user-attachments/assets/d583ff42-0816-483e-9c26-da0a122bb7a7)

Will investigate further on why you're experiencing this issue on extension loading.

Could you check the logs of the extension (debug level) and check for `codeInsights/annotations.json` or something unusual like an error?

Note that this is the output panel, with Datadog selected as the output, and debug level selected (in the wheel). Then reload VS Code Window and check what you see in there.

![Image](https://github.com/user-attachments/assets/7929f5d8-ffb4-4622-aaff-8177eb9609bf)

**Comment by robertohuertasm** [comment]
@pbernery, if you prefer, we can meet over zoom, google meet or whatever works best for you, and check the logs together. Send me an email to roberto.huertas@datadoghq.com if you prefer that option, and we can set something up. Cheers!

**Comment by robertohuertasm** [comment]
@pbernery one theory that we have is that for some reason, when you open a project, the extension is not detecting your repository and the request doesn't return anything because of that.

Note that the extension relies on the git extension to detect your repositories. If for some reason that extension is not responsive, we cannot do much. We currently have a retry mechanism with certain incremental delays, so the extension can take up to 55 secs to get the repository. 

It would be nice to understand how much it takes for you to get something (I mean any message, not really code insights) into the code insights view on the first load. If it takes 55 secs or something like that, then it's the case where we cannot get the repository. If it takes less, that means that we received an error from the git extension.

Again, feel free to ping me to my email to discuss this in a more extended way.

**Comment by robertohuertasm** [comment]
Can you let me know which is the repo where you're seeing this behavior? According to the traces we're seeing here you have one repo under your personal user and another one under your org (I don't want to give more details here). Are you experiencing the issue of having to manually load the code insights with both of them?

**Comment by robertohuertasm** [comment]
Great to hear that. I'm closing the issue. Let us know if you experience something similar again. Thanks!
